server:
  port: 23020
  servlet:
    context-path: /cloud-producer


spring:
  mvc.throw-exception-if-no-handler-found: true
  resources.add-mappings: false
  application:
    name: cloud-producer



#eureka
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://127.0.0.1:20000/eureka/
